package catalog

// builtinModels returns a baked-in snapshot of well-known Anthropic models.
// Pricing is approximate public pricing (USD / 1M tokens) as of 2025-07.
// This snapshot is used when the network is unavailable and no cache exists.
func builtinModels() []ModelInfo {
	return []ModelInfo{
		{
			ID:              "claude-opus-4-7",
			Name:            "Claude Opus 4.7",
			Provider:        "anthropic",
			ContextWindow:   1_000_000,
			InputCostPer1M:  15.0,
			OutputCostPer1M: 75.0,
			ToolUse:         true,
			Vision:          true,
			Thinking:        true,
		},
		{
			ID:              "claude-sonnet-4-6",
			Name:            "Claude Sonnet 4.6",
			Provider:        "anthropic",
			ContextWindow:   1_000_000,
			InputCostPer1M:  3.0,
			OutputCostPer1M: 15.0,
			ToolUse:         true,
			Vision:          true,
			Thinking:        false,
		},
		{
			ID:              "claude-haiku-4-5-20251001",
			Name:            "Claude Haiku 4.5",
			Provider:        "anthropic",
			ContextWindow:   200_000,
			InputCostPer1M:  0.8,
			OutputCostPer1M: 4.0,
			ToolUse:         true,
			Vision:          true,
			Thinking:        false,
		},
		{
			ID:              "claude-opus-4-5",
			Name:            "Claude Opus 4.5",
			Provider:        "anthropic",
			ContextWindow:   200_000,
			InputCostPer1M:  15.0,
			OutputCostPer1M: 75.0,
			ToolUse:         true,
			Vision:          true,
			Thinking:        true,
		},
		{
			ID:              "claude-sonnet-4-5",
			Name:            "Claude Sonnet 4.5",
			Provider:        "anthropic",
			ContextWindow:   200_000,
			InputCostPer1M:  3.0,
			OutputCostPer1M: 15.0,
			ToolUse:         true,
			Vision:          true,
			Thinking:        false,
		},
		{
			ID:              "claude-3-5-sonnet-20241022",
			Name:            "Claude 3.5 Sonnet",
			Provider:        "anthropic",
			ContextWindow:   200_000,
			InputCostPer1M:  3.0,
			OutputCostPer1M: 15.0,
			ToolUse:         true,
			Vision:          true,
			Thinking:        false,
		},
		{
			ID:              "claude-3-5-haiku-20241022",
			Name:            "Claude 3.5 Haiku",
			Provider:        "anthropic",
			ContextWindow:   200_000,
			InputCostPer1M:  0.8,
			OutputCostPer1M: 4.0,
			ToolUse:         true,
			Vision:          false,
			Thinking:        false,
		},
		{
			ID:              "claude-3-opus-20240229",
			Name:            "Claude 3 Opus",
			Provider:        "anthropic",
			ContextWindow:   200_000,
			InputCostPer1M:  15.0,
			OutputCostPer1M: 75.0,
			ToolUse:         true,
			Vision:          true,
			Thinking:        false,
		},
	}
}
